### ISSUE TITLE
Dead people included in Total Population

### ISSUE THREAD

**Issue by NabinAch** [manishlamichhane/genetic#4]
`@property`
    `def total_population(self):`
        `return len(self.male_population) + len(self.female_population)`

This is counting dead people as well.

**Comment by NabinAch** [comment]
I see it now, select function is removing dead people after every round so why not remove dead people immediately after they died?

**Comment by NabinAch** [comment]
#6 Fix pushed in pull request

**Comment by 9radiopassive0** [comment]
I cant track the index of the randomly selected male object in the self.male_population. Hence, a dedicated select function does the job of removing the dead or selecting only the alive ones.
