### ISSUE TITLE
Male are dying to have sex with same infertile women

### ISSUE THREAD

**Issue by NabinAch** [manishlamichhane/genetic#5]
` @staticmethod`
  `  def choose_female(female_population):`
`        for female in female_population:`
       `     if female.is_alive and not female.is_pregnent:`
        `        return female`

As this is linear search, If the female is not fertile, same female will always get chosen and in every loop a male is getting killed to have sex with same unfertile women until every male expect one has died. :(

**Comment by NabinAch** [comment]
#6 Fix pushed in pull request

**Comment by 9radiopassive0** [comment]
Randomly assigining Fertility is making things complicated. In new version, I have set the is_fertile attribute to be true.
